### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by solomonxie** [solomonxie/emailpy#1]
- [x] Retrieve emails (Class: EmailServer)
    - [x] Login & logout server
    - [x] Retrive email list
    - [x] Retrieve an email according to its index
- [x] Parse email (Class: Email)
    - [x] Export email raw message
    - [x] Load & decode headers
    - [x] Load multi-parts
    - [x] Load & export attachments
    - [x] Decode text content according to its Transfer-encoding & Charset
    - [x] Load & export plain text content
    - [x] Load & export HTML content
    - [ ] Optimize algorithm
        - [ ] ~Export each mail right after retrieved~
- [x] Send emails (Class: Yagmail)
    - [ ] ?
- [ ] Handle email tasks (Class: EmailTask)
    - [ ] Authentication
        - [ ] Token (only available at the same day)
    - [ ] Scheduled sending emails
        - [ ] Read task-calendar
        - [ ] Convert Markdown file to HTML-Email and send
    - [ ] Monitor system status and send alert emails
        - [ ] Shadowsocks connection
        - [ ] Daily network stats
    - [ ] Note taking
        - [ ] Automatically send content to specific Github issues or comment
    - [ ] Receive command from email and run locally
        - [ ] Reboot system
        - [ ] Send system current status
